spring:
  datasource:
    url: jdbc:h2:mem:testdb
    name: testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true